### ISSUE TITLE
Add an AI Directory website

### ISSUE THREAD

**Issue by Songyan992** [fmhy/edit#2407]
### Type

Site suggestion

### Add additional context

OkeiAI is an AI tools and resources navigation platform. Users can submit their own AI tools, and once approved by the platform, the tools will be displayed and recommended. The website focuses on providing resources related to machine learning, deep learning, NLP, and more.
Visit: https://okeiai.com/

**Comment by nbats** [comment]
Thanks for sharing we'll take a look
