### ISSUE TITLE
Can we add genealogy softwares?

### ISSUE THREAD

**Issue by usernamex** [fmhy/edit#2414]
### Type

Site suggestion

### Add additional context

Listed is the most popular genealogy softwares: https://en.wikipedia.org/wiki/Comparison_of_genealogy_software

Here are the free ones:
1. [Ancestris](https://en.wikipedia.org/w/index.php?title=Ancestris&action=edit&redlink=1)
2. [GenealogyJ](https://en.wikipedia.org/wiki/GenealogyJ)
3. [Gramps](https://en.wikipedia.org/wiki/Gramps_(software))
4. [Legacy Family Tree](https://en.wikipedia.org/wiki/Legacy_Family_Tree)
5. [LifeLines](https://en.wikipedia.org/wiki/LifeLines)
6. [Personal Ancestral File](https://en.wikipedia.org/wiki/Personal_Ancestral_File)

**Comment by nbats** [comment]
Sorry but a lot of them are considered a bit scammy / shady so we've always avoided them.
