### ISSUE TITLE
Removal of RetroPlus, as the repo is now archived.

### ISSUE THREAD

**Issue by AzhamProdLive** [fmhy/edit#2422]
### Type

Bad sites

### Add additional context

Under https://fmhy.net/linuxguide#linux-gaming, RetroPlus is still shown there, however, the creator of the repo archived it and removed the project from FlatHub

From his own words : "I decided to end support for RetroPlus due to lack of interest and the fact Nintendo hit my main ROMs source which was Vimm's Lair." 
https://github.com/Vysp3r/RetroPlus

**Comment by nbats** [comment]
Will do thanks for the heads up
