### ISSUE TITLE
[ADD] Privacy-DNS - A free, encrypted, no-logs and privacy-oriented DNS that blocks tracking, ads and phishing, with support for DoH, DoT, DoQ and DNSCrypt & Anonymized DNSCrypt proxy.

### ISSUE THREAD

**Issue by scriptzteam** [fmhy/edit#2429]
### Type
Site suggestion

https://privacy-dns.pw/

**Category: Free DNS Servers** 

A free, encrypted, no-logs and privacy-oriented DNS that blocks tracking, ads and phishing, with support for DoH, DoT, DoQ and DNSCrypt & Anonymized DNSCrypt proxy.

**Comment by nbats** [comment]
ty its in our queue so we'll check it out when we can
