### ISSUE TITLE
[ADD] Web Network Tools

### ISSUE THREAD

**Issue by scriptzteam** [fmhy/edit#2431]
### Type

Site suggestion

### Add additional context

Hi, wanna share some web tools, you might find them useful.

Ping/traceroute/dns/http from multiple locations:
https://ping.s-e-r-v-e-r.pw/

Send packets ( IP to 51.15.51.3 and PORT to 1337 ) and show them online:
https://dump.packetnoise.monster/
https://github.com/PaCkEtNoIsE

Send few TCP packets throught Tor:
https://hello.packetnoise.monster/
https://github.com/PaCkEtNoIsE/HELLO

Send spoofed TCP packets:
https://spoof.packetnoise.monster/
https://github.com/PaCkEtNoIsE/SPOOF

Certificates of IP:PORT or DOMAIN throught Tor:
http://cert.packetnoise.monster/1.1.1.1/443
http://cert.packetnoise.monster/github.com/443

DNS:
https://dns.packetnoise.monster/dns.google/A
https://dns.packetnoise.monster/1.1.1.1/PTR

**Comment by nbats** [comment]
much appreciated, I'll add them to our link queue
