### ISSUE TITLE
"Direct Links Out"  last update 2017

### ISSUE THREAD

**Issue by HDark15** [fmhy/edit#2433]
### Type

Site suggestion

### Add additional context

https://openuserjs.org/scripts/nokeya/Direct_links_out
https://github.com/nokeya/direct-links-out
Has never been updated since 2017, but there'a a fork

https://github.com/XX-J/Direct-links-out
Last update Nov 13, 2023

**Comment by nbats** [comment]
I'll get it replaced thanks for the update
