### ISSUE TITLE
YouTube Livestreams Theater Mode

### ISSUE THREAD

**Issue by HDark15** [fmhy/edit#2437]
### Type

Site suggestion

### Add additional context

YouTube Livestreams Theater Mode is a browser extension that provides an enhanced theater mode for an improved viewing experience of livestreams and premiers on YouTube. 
Has source code.
https://www.napalighost.com/youtube-livestreams-theater-mode

[Chrome Web Store](https://chrome.google.com/webstore/detail/youtube-livestreams-theat/cmjhejfkhdonjimgkinjdombabgfbcal)(Google Chrome, Opera, Microsoft Edge and more)
[Firefox Add-ons](https://addons.mozilla.org/en/firefox/addon/youtubelivestreamstheatermode/)(Firefox)

**Comment by nbats** [comment]
we'll take a look thanks for sharing
