### ISSUE TITLE
enhanced-h264ify

### ISSUE THREAD

**Issue by HDark15** [fmhy/edit#2438]
### Type

Site suggestion

### Add additional context

enhanced-h264ify is a fork of well-known h264ify extension for Firefox/Chrome which blocks VP8/VP9 codecs on YouTube, so that you can use H264 only. This may be useful because there are lots of devices on the market which support H264 hardware decoding and do not support VP8/VP9. 
Good for low spec devices.

This extension has new features such as manual blocking of H264, VP8, VP9, AV1, Opus, AAC codecs and 60fps video. By default it blocks everything but H264 and 60fps video. It works only on YouTube.
![1K84DSeTrt](https://github.com/user-attachments/assets/136b5c23-612d-4ae8-b11d-fcca027b23d9)

https://github.com/alextrv/enhanced-h264ify

**Comment by nbats** [comment]
added to queue ty
