### ISSUE TITLE
[Firefox] Audio Compressor

### ISSUE THREAD

**Issue by HDark15** [fmhy/edit#2439]
### Type

Site suggestion

### Add additional context

Audio Compressor is an addon that uses dynamic range compression to make sound volumes more even.
There are presets for different levels of compression. You can customize the default settings or the settings for a specific site or page.

There are some sites it doesn't work with, cross-origin browser security blocks scripts from modifying audio/video from a different host. As far as I know there's no way around this.
Probably won't work for embedded audio/video.

https://github.com/vatara/firefox-audio-compressor/
https://addons.mozilla.org/en-US/firefox/addon/audio-compressor/

**Comment by nbats** [comment]
added to queue ty
