### ISSUE TITLE
Remove Lite-GPT from Online chatbot

### ISSUE THREAD

**Issue by therightrequest** [fmhy/edit#2444]
### Type

Bad sites

### Add additional context

Lite-GPT has shutdown their services on 2024-09-29
![{6644A02C-95C2-4F4B-9640-2EAC9C050372}](https://github.com/user-attachments/assets/c1e1635e-c16a-4af8-8179-6bf23fa1acdd)

Translation:
Hahaha, at this point, this site has stopped serving, just like the previous "Lea Platform". It turns out that "content is not controlled" is an effect rather than a cause. Because of those services used, "content is not controlled". No matter what measures you take, as long as those three letters appear, it means it is not controlled, haha.
I once thought that as long as we abide by the law, it will be fine. However, in reality, it will be very complicated, society is complicated, and people's hearts are even more complicated.
I understand why everyone says I am too honest, and I understand why everyone is trying to persuade me not to register. I understand why my colleagues always say to me contemptuously as if they have been through it before: "We are blocked at most, but you can't even drive!"
Today someone said, "Since users are all free, why do you have to think about them?" I was completely confused when I heard this sentence. It was like "Why should you help me if you didn't hit me?" It made me give up instantly. When I came to this site, I also gave up my “naivety”.
Let me help you one last time: the source code of this website has been made public, and the source code is in the largest open source community in the world. I won't be maintaining this site anymore, got it.
Please stop contacting me and treat me as dead. Oh, I've never "lived".
Since then, there has been one less naive programmer in the world.

**Comment by Setsuwaa** [comment]
What's the link for this? ~16 hours ago the link for Lite-GPT was changed and that link seems to be working fine - #2434 

More context would be nice.

**Comment by nbats** [comment]
Will do thanks for letting us know

**Comment by helix-nuked** [comment]
> What's the link for this? ~16 hours ago the link for Lite-GPT was changed and that link seems to be working fine - #2434
> 
> More context would be nice.

Here was the email i got that the owner was changed

![image](https://github.com/user-attachments/assets/a40e85a0-aa18-4dfb-b57f-c33d0592353e)

**Comment by helix-nuked** [comment]
couldn't blur the mail but whatever

**Comment by helix-nuked** [comment]
and another one here:
![image](https://github.com/user-attachments/assets/6e056015-576e-4f74-b137-3ccb78c5c271)

**Comment by helix-nuked** [comment]
it would be better if this issue was re-opened
