### ISSUE TITLE
Re-Add Lite-GPT

### ISSUE THREAD

**Issue by helix-nuked** [fmhy/edit#2451]
### Type

Site suggestion

### Add additional context

http://lite.fuckicoding.com should be added with just a warning to use vpn
see the issue #2444 and i sent some screenshots

**Comment by Setsuwaa** [comment]
+1
Idk why it was removed at all lol, unless it was because it's not secure.

**Comment by nbats** [comment]
its not loading for me

**Comment by nbats** [comment]
Alright I'll add it back to queue and see what people say### 

- [ ] - > [`_****_`](url)

**Comment by nbats** [comment]
added back to queue
