### ISSUE TITLE
Samsung Tools — Odin, Heimdall, Heimdoo, Bifrost and tools for other OEMs.

### ISSUE THREAD

**Issue by yuzamei2854** [fmhy/edit#2464]
### Type

Site suggestion

### Add additional context

Hello, I wanted to give some suggestions of tools that could be useful for Samsung users, I feel that their proper place would be in the [Root/Flash](https://fmhy.net/android-iosguide#root-flash) section.

1. [Odin](https://xdaforums.com/t/patched-odin-3-13-1.3762572/): to flash files on a Samsung device. (It would also be interesting to add a note to install [Samsung USB drivers](https://developer.samsung.com/android-usb-driver).)
2. [Heimdall](https://glassechidna.com.au/heimdall/): similar function to Odin, but it's a CLI tool, and it's available for platforms other than Windows. 
3. [Heimdoo](https://github.com/RohitVerma882/Heimdoo): Heimdall port for Android.
4. [Bifrost](https://github.com/zacharee/SamloaderKotlin): to download the firmware for Samsung mobile devices.

There are also a few things I haven't gotten around to testing that might be useful in other OEMs.

1. [MIUI Roms](https://t.me/miuiappshare): Seems to be an application for downloading the firmware for Xiaomi mobile devices.
2. [Motorola's Software Fix Tool](https://en-us.support.motorola.com/app/softwarefix): Seems to be a rescue program for Motorola mobile devices, it seems to download and install the latest firmware for that device. 
3. [Moto Flash Tool](https://github.com/Vachounet/moto_flash_tool): It seems to be a CLI tool for flashing firmware on Motorola mobile devices, it is also available for platforms other than Windows.

**Comment by nbats** [comment]
Thanks for the suggestions, I added this pull request to our link queue, so we'll look through them when we can.
