### ISSUE TITLE
removal of polonium games from the fmhy megathread

### ISSUE THREAD

**Issue by enzuccio-ctrl** [fmhy/edit#2480]
### Type

Bad sites

### Add additional context

![Cattura nosteam](https://github.com/user-attachments/assets/d00a6961-454a-4aa4-b799-64772d3f8702)

I downloaded bioshock 2 from this site and went on properties and on comment saw written "Play Bioshock 2 nosTEAM" because nosTEAM is an unsafe publisher and is knownfor injecting crypto miners and malware in their cracks being mentioned in the properties of a file is sussy and on their site unlike SteamRIP or other sites on the megathread and they don't list crack source or game version

**Comment by nbats** [comment]
alright thanks for the heads up, I just let the owners know its unsafe so we'll see if they remove it, and if not we'll remove the site

**Comment by nbats** [comment]
update the owners have removed the game
