### ISSUE TITLE
<title>Useful sites job board submission

### ISSUE THREAD

**Issue by CodingCossack** [fmhy/edit#2484]
### Type

Site suggestion

### Add additional context

Hi. Hope all is well. Love the website and congrats on the large discord following. Was hoping you could add a job board to your useful sites section: https://chefjobsnear.me

[US Chef Jobs](https://chefjobsnear.me) - Find Culinary roles across the US

**Comment by nbats** [comment]
thanks for sharing, I added to queue so we'll check it out when we can
