### ISSUE TITLE
[UPDATE] Safari Adblockers for Mac

### ISSUE THREAD

**Issue by TheKivster** [fmhy/edit#2491]
### Type

Bad sites

### Add additional context

In the Mac Adblock / Privacy section it shows safari adblockers that are only for iPhone and not Mac.

**Comment by nbats** [comment]
Gotcha I'll get them removed, ty for the heads up

**Comment by TheKivster** [comment]
Will they be replaced with real Mac Safari adblockers?

**Comment by nbats** [comment]
possibly if you or someone else send some good ones
