### ISSUE TITLE
FMHY SafeGuard Extension

### ISSUE THREAD

**Issue by kenhendricks00** [fmhy/edit#2506]
### Type

Site suggestion

### Add additional context

Hey, I've been working on the FMHY SafeGuard Extension and think it's complete enough to be listed.
Of course, I will continue to update, fix bugs, and accept any contributions to improve the project.
Links:
[GitHub](https://github.com/kenhendricks00/FMHY-SafeGuard)
[Firefox](https://addons.mozilla.org/en-US/firefox/addon/fmhy-safeguard/)

**Comment by nbats** [comment]
Looks good thank you for all the work, I just got it added to the top of the unsafe section and we'll do an announcement once more people have tested it.
