### ISSUE TITLE
CrackingCity is an unsafe site

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2508]
### Type

Bad sites

### Add additional context

Their IDM crack is a trojan. It deletes itself. [Triage gives it a score of 8/10](https://tria.ge/241016-rndcjatepa) and declares it an adware, spyware, stealer and trojan. So I think it's an unsafe site. So please add it to the "Unsafe sites" list.

**Comment by nbats** [comment]
Alright ty for the heads up, we'll take a look and and get it added after we confirm

**Comment by nbats** [comment]
Quick update we got it added to unsafe

**Comment by kvhjdffv** [comment]
Thanks :3
