### ISSUE TITLE
A website I made but is completely open source

### ISSUE THREAD

**Issue by gocygo** [fmhy/edit#2509]
### Type

Site suggestion

### Add additional context

https://groq.gocygo.com is a site I just finished making, I’ll be working on it as well as making the rest of gocygo.com a blog/free site. There’s still some broken features and a lot missing right now. It’s in my GitHub if you’d like to look at the source code but I thought it would be cool if people could take advantage of it. :)

**Comment by nbats** [comment]
Thanks for sharing, I'll add it to our queue and we'll check it out
