### ISSUE TITLE
Allow leeches/debrid section

### ISSUE THREAD

**Issue by Vojtak42** [fmhy/edit#2513]
### Type

Wiki section suggestion

### Add additional context

Hi,
I think it is time to allow Leeches/debrid section because the Miraheze wiki seems outdated and doesnt allow contributions from community.

Btw you should uipdate this template as [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) link doesnt work nor the [Contribution Guide](https://rentry.co/Contrib-Guide).

Thanks for your consideration.

**Comment by nbats** [comment]
Here's the new single page link: https://api.fmhy.net/single-page but I dont have the edit code for the other sadly sorry.

As far as the section goes, if people send in enough good stuff we could consider it, we just dont have much as of now.
