### ISSUE TITLE
[Site suggestion] aniwave.best

### ISSUE THREAD

**Issue by mpaunovic** [fmhy/edit#2516]
### Type

Site suggestion

### Add additional context

aniwave.best looks like a decent aniwave.to successor. Please consider adding it to the Movies / TV / Anime section.

Thank you!

**Comment by nbats** [comment]
thanks for sharing we'll check it out soon

**Comment by UdaySriHarsha** [comment]
this is a complete clone with sources from animixplay.tube, and the loading animation is a pickachu
@nbats

**Comment by nbats** [comment]
alright thanks for the heads up, I'll get it added with that
