### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by mathieufd** [fmhy/edit#2522]
### Type

Site suggestion

### Add additional context

https://jeez.me is a good streaming concept. You import a Google Sheet full of sources and the plateform is ready
Google Sheet updated by the Jeez team : https://jeez.me/sources/?sheet=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vRF-J_CcEzfzuvi3g7X90W5yajobn1F19BikbeMJKxAX7S8NR3trCydePl4I4a9Eler8038-QV5AWH0%2Fpub%3Foutput%3Dcsv

Thank you

**Comment by nbats** [comment]
we'll check it out thanks for sharing
