### ISSUE TITLE
Taiwebs is not safe

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2523]
### Type

Bad sites

### Add additional context

Their Start11 patch is [just the FileCR one](https://rentry.org/taiwebsunsafe). So I think it's unsafe. Please add it to the "Unsafe Sites" list. Thanks.

**Comment by nbats** [comment]
Thank you we'll take a look and get it added soon

**Comment by kvhjdffv** [comment]
@nbats Thank you so much. Sorry if it's too much. But, would you mind linking my original rentry as well? I won't mind a bit if there's an with that though.
