### ISSUE TITLE
Dead link in the unsafe sites section

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2529]
### Type

Wiki Suggestion

### Add additional context

Hello, I just want to let you know that the imgbb link to show that Taiwebs is a malicious site.... isn't working.
![2024-10-26 16_31_30-Window](https://github.com/user-attachments/assets/96ad58b4-c79e-492f-9103-961fff5396d9)
![2024-10-26 16_31_58-Window](https://github.com/user-attachments/assets/17ab30b6-cbac-4113-bd91-f97ede62f415)
Please consider fixing the link or linking to [my original rentry](https://rentry.org/taiwebsunsafe). Have a great day.

**Comment by nbats** [comment]
Will do thanks for the heads up

**Comment by kvhjdffv** [comment]
Thank you so much <3
