### ISSUE TITLE
You can actually add all your sites to raindrop.io and host them for free.

### ISSUE THREAD

**Issue by David7ce** [fmhy/edit#2538]
Here is an example of a project hosted on raindrop.io where there are more than 30k sites saved using the free account. raindrop.io allows you to share bookmarks for free and it is a great way to navigate links and view them in "card mode" which is more visual and optimized for large screens. Also Raindrop.io allows you to import a large list of bookmarks, which is a great way to back up content.

Here's the example of a big raindrop collection of links called Interneto, and here are the links of [Interneto homesites](https://raindrop.io/Interneto/homesite-37376440)

![Screenshot 2024-10-28 at 00-03-45 Homesite](https://github.com/user-attachments/assets/a1dbbf12-6fe5-4e6b-bdce-88e69a125e7a)

**Comment by nbats** [comment]
Thats cool but the issue is getting someone to match it 1:1 anytime we add something new, or remove something from FMHY.

**Comment by nbats** [comment]
Possibly, its just you have to understand FMHY is so time consuming already as it is, its tough to find motivation or anyone to  help with a side project like this when we add / remove so many sites daily. If you wanna take it on feel free, I just cant myself really.

**Comment by David7ce** [comment]
I understand, I do a similar project but not exactly as FMHY on raindrop.io. I know it is very time consuming, and in this case it seems there's no easy way to automatize the process.

**Comment by David7ce** [comment]
I've added the list of bookmarks to my Interneto project on raindrop. Here's the link: [raindrop.io/Interneto/fmhy](https://raindrop.io/Interneto/fmhy-49227776).

Now the main problem is keeping it up to date with the main.

I've been doing this a similar project with [Internet links](https://raindrop.io/Interneto) for a couple of years and I think I've learned how to classify things in a good way for big classification systems as a result.

FMHY is a decent classification system, but I think it might not be the best choice if it keeps growing. I think things should be classified by their main purpose or goal. Things like the technology used, the language, the operating system, and the author aren't as important and should be listed or considered as tags or extra information. The main folders should be based on their purpose.

Most of the websites we classified are web apps or interfaces with databases. If there's a static website, it probably won't be listed because it'd be a blog or some kind of information site. So, for me, the "real" classification comes down to web apps or basically "real apps". Here's the system that I follows under "Software" category:

![Image] (https://github.com/user-attachments/assets/c290a9ac-44eb-47f8-a8a2-c7ddf88fd578)

One project that does this really well is AlternativeTo (starred on FMHY). For me, it's the best classification database for apps. It's well organized with main categories and apps inside, plus tags and extra info with multiple links to compatibility OS (Android, iOS, Linux, macOS, Windows), open-source repositories, comments, and reviews.

Classifying things is tough.
- One link can be in multiple categories depending on the compatibility system (OS or offline/online). I try to keep it simple. So links should be listed as their main goal, either as homesite link or, if not, as repository link and the compatibility OS as a tag or extra attribute.
- Then there's the issue of keeping track of all the different links in the chain, as well as discontinued apps, new apps, and so on.
- Finally, there's the issue of creating an effective interface for navigating links. A plain text index like FMHY is straightforward and effective, but it lacks visual appeal and intuitiveness and it's not easy to navigate. I think showing links as icons or navigating in a graph or island map would be great, but it would require a solid app with a database that allows that.

I'm just sharing this because I like FMHY a lot. I think it's good, but the main problem I found is the classification system and the way to navigate with the exponential growth of links.

A good app to classify links like raindrop.io and a good classification is a good solution. However keeping things simple like yours a with markdown files with links hosted and manage with GitHub is good solution.

**Comment by nbats** [comment]
Very cool thanks for doing that, I'll send it to our discord and see what people want to do with it.

As far as classification goes, you do have a lot of great ideas and you've given me a lot of think about, but I will admit being 6 years into FMHY has made it a bit hard to make a bunch of big changes all at once. It doesn't mean changes cant happen, we just usually have to do each idea one at a time if that makes sense. I will keep this bookmarked though and and take things into consideration.

**Comment by David7ce** [comment]
> Very cool thanks for doing that, I'll send it to our discord and see what people want to do with it.
> 
> As far as classification goes, you do have a lot of great ideas and you've given me a lot of think about, but I will admit being 6 years into FMHY has made it a bit hard to make a bunch of big changes all at once. It doesn't mean changes cant happen, we just usually have to do each idea one at a time if that makes sense. I will keep this bookmarked though and and take things into consideration.

Your classification system is very solid and is centered mainly in FOSS apps, if I'm not mistaken you don't host proprietary apps, so that's a very distinctive view.

The main problem with classification system is when things keep growing in number of links, topics of links and extra information. That's when things get messy, if there are less than 1k links is more and less easy. But nowadays FMHY is not only for piracy guides or content is so much bigger.

My point is you can stay with a simple classification system with a limited number of links or adapt to more cohesive system for very big classification system.

One simple solution is not add to much noise, just good content to keep a good cohesive database. There is a proverb in Spanish "el que mucho abarca poco aprieta" = "he who grasps too much grasps too little".

Keep the good work ;)

**Comment by nbats** [comment]
@David7ce I see you sent this again with a new site which is very cool, but the issue with us adding it is 1 it contains so much stuff its hard for us to be sure its all safe, and 2 it has a whole section dedicated to nothing but multiplayer cheats. FMHY doesn't add anything to do with ruining games for others like that.

**Comment by David7ce** [comment]
Hey @nbats, I just sent you the site <https://interneto.github.io/>, which is a web directory I've been working on at raindrop.io since 2020. I recently wrote a little script to migrate from CSV to a list of markdown articles with links (like FMHY does).

I totally get why you're not allowing the listing of my web directory, but I'm a bit puzzled. I totally understand where you're coming from, and I really appreciate your concern. I'm just wondering if you're saying that, because it's big and contains three open-source cheats, it should be denied? I'm a pretty honest person, but I'd still list it because it's open source. That way, someone can test it locally and know that it exists. It's like a list of repositories that contain a database of classified malware. It's not bad at all! It's just educational. How it's used is another matter, but everything is dual. 

Once more, they're just URLs. Websites themselves aren't malware. If a website seems a little suspicious, it's always best to check if you need to consent, download, install, or register. As a user, it's always important to review links and certificates.

**Comment by nbats** [comment]
> because it's big and contains three open-source cheats, it should be denied

FMHY has never once in its history added anything to do with cheating in *multiplayer* games. Single player modding is fine, but we just don't want to promote it in multiplayer. 

> Websites themselves aren't malware

Fair enough but that doesn't mean they cant host malware, its just such a massive list of things its so hard for us to confirm if any of it has been tested for safty or not
