### ISSUE TITLE
Re: Dead link in the unsafe sites section

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2544]
### Type

Site suggestion

### Add additional context

Fake Z-Lib Sites / **2** doesn't work

![2024-10-29 17_03_42-Unsafe Sites • freemediaheckyeah - Brave](https://github.com/user-attachments/assets/cbab4e75-59a8-4aff-b6cf-681741135601)
![2024-10-29 17_04_22-That page doesn't exist (404) — ImgBB - AdsBypasser - Brave](https://github.com/user-attachments/assets/32a9b016-d4b2-4a8b-ba09-c2cbf4a5c39e)

**Comment by nbats** [comment]
strange it loads fine for me

**Comment by kvhjdffv** [comment]
@nbats It's still not fixed btw.
![2024-10-29 20_46_14-That page doesn't exist (404) — ImgBB - AdsBypasser - Brave](https://github.com/user-attachments/assets/5f0cc2a9-dfa5-4a18-bf75-e5642c837b18)

Would you mind switching to a new URL?

**Comment by nbats** [comment]
Alright I just updated the old one and also added a imgur link
