### ISSUE TITLE
Appnee might not be safe

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2546]
### Type

(Apparent) Bad sites

### Add additional context

Hey, so I just came across [this reddit post](https://www.reddit.com/r/Piracy/comments/1gffxop/appnee_is_not_safe_anymore/) claiming that Appnee (a site in the r/Piracy megathread) isn't safe. Can you investigate this and potentially add it to the unsafe sites list? Thanks.

[Screenshot (in case of it getting taken down)](https://i.ibb.co.com/zFbLcVS/The-Post.png)
[VirusTotal scan](https://www.virustotal.com/gui/file/76a2db9dc32284806d116c8278b44832f03826cf2cb8c2988fa0515dfa6433b6)

**Comment by nbats** [comment]
Thanks for the heads up we'll take a look, but at first glace it looks like some sort of patcher.

**Comment by MIOGMIOG** [comment]
Appnee got added to unsafe sites in f3d9941
Thanks for letting us know!
