### ISSUE TITLE
Add a halloween theme to the site on October 31st

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2548]
### Type

Site suggestion

### Add additional context

Hey, since halloween's tomorrow, I was wondering if you could add some special themes to the site. I don't know if you have something like this in mind already. But I still think it's sort of cool.

**Comment by nbats** [comment]
I'm sorry it would be cool but I just dont think its possible given how soon it is. Maybe next year we can plan something further in advanced and ask for help from some of our resident artists.

**Comment by kvhjdffv** [comment]
@nbats Do you think that you can (possibly) add  something else to the site in the meantime? Like some halloween art throughout the site should be fine (for now).

**Comment by nbats** [comment]
I mean I'm not an artist myself so I wouldn't even know where to begin, but if you have ideas you're welcome to send pull requests.

**Comment by kvhjdffv** [comment]
@nbats Neither am I. And I don't know coding enough to make a single pull request. So guess it has to wait :(
