### ISSUE TITLE
Update the Discord invite link

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2551]
### Type

Site suggestion

### Add additional context

Hey, so I tried to join the FMHY discord server but the invite link expired.

Here're some screenshots of exactly where I went to get to this point (for no reason):

![2024-11-01 11_34_14-Window](https://github.com/user-attachments/assets/360b9fc6-d49e-4d8e-9a25-8e019944f4f1)
![2024-11-01 11_34_43-Window](https://github.com/user-attachments/assets/cccf9ce3-35e8-4911-b1bb-4e13bc1f1fd3)
![2024-11-01 11_34_57-Window](https://github.com/user-attachments/assets/d1dd6716-7bd5-402c-b5ef-793f399a7bb8)
![2024-11-01 11_35_08-Window](https://github.com/user-attachments/assets/32f39c63-62f2-4899-b08c-8fffad3964b3)
![2024-11-01 11_35_40-Window](https://github.com/user-attachments/assets/52e9e4f1-75e9-4ecf-87b1-eac822a62b75)

Consider updating the invite link (so that I can join the server)

*By the way, I wish you guys a (late) very happy Halloween* 🎃

**Comment by nbats** [comment]
Sorry we're semi-private now so lots of old links will need to be updated. You can get one here every friday.

https://rentry.co/fmhy-invite

**Comment by kvhjdffv** [comment]
@nbats Where can I find this link (in the wiki)?

**Comment by kvhjdffv** [comment]
@nbats Alright
