### ISSUE TITLE
Remove duplicate links

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2554]
### Type

Site suggestion

### Add additional context

Remove one or the other
![2024-11-01 22_07_29-Window](https://github.com/user-attachments/assets/b6b37572-0352-4f7f-809d-a7536d9a492a)
![2024-11-01 22_08_08-Window](https://github.com/user-attachments/assets/15e5c589-6999-4c52-82c8-346d30eff151)

**Comment by nbats** [comment]
This is on purpose so people can find it more easily. The discord one would only show on the front page otherwise, or the github only when you're at the top.

**Comment by kvhjdffv** [comment]
@nbats Alright, I get the GitHub one. But, why the discord one? I think you can remove one of them.

![2024-11-02 08_30_23-](https://github.com/user-attachments/assets/44602c02-5204-4772-bb41-741346e0d537)

**Comment by nbats** [comment]
I mean we could it just helps it stand out a bit to have a bigger button on the front page

**Comment by kvhjdffv** [comment]
@nbats Alright whatever. I don't want to argue with you. It's just that I THINK having duplicate links looks weird.
