### ISSUE TITLE
Add "https://ktp-cracks.neocities.org/"

### ISSUE THREAD

**Issue by KraysThePoet** [fmhy/edit#2555]
### Type

Site suggestion

### Add additional context

It's my own site and in my opinion I can consider myself to be very or at least decently trusted

**Comment by KraysThePoet** [comment]
btw it would belong into "Gaming/Emulation" under "Download Games"

**Comment by nbats** [comment]
Thanks for sharing we'll check it out when we can

**Comment by nbats** [comment]
Our scans came back clean so far, but one issue is that your game sources aren't listed anywhere. I know you don't have individual game pages, but maybe you could list the source in the bottom right of each games cover.

**Comment by KraysThePoet** [comment]
Hello, first of all, thank you for the (faster than ever anticipated) response, and apologies for my rather late response! I'm not sure whether you responded prior to me adding this, but on the top of the page there is now a string of text, that (I think more or less) explains what the sources of the games are. Please let me know, if this is what you imagined by "sources", and feel free to further specify/explain if anything is missing and/or not specific enough. Again, thank you for the quick response, and I hope this message will find you well

**Comment by nbats** [comment]
Yeah that looks good thanks for adding it, right now it seems every link is down though so not sure what happened there.

**Comment by KraysThePoet** [comment]
Thanks for making me aware of this issue! I immediately recognized what the problem was, and am currently working on bringing all games back up! (Some games have already been fixed). I will reach out again, once the issue is fully resolved

**Comment by KraysThePoet** [comment]
Every link is back up, and the site now functions as it should. Again, big thanks of making me aware of this issue

**Comment by nbats** [comment]
Alright thanks for the update, I'll move it back to testing and once thats done we'll get it added to fmhy

**Comment by KraysThePoet** [comment]
Wanted to reach out due to the recent events at buzzheavier. All our files are locked and buzzheavier was the only filehost I ever used. The majority of games are lost, and we're completely useless, apart of actually 3 games that still work/are downloadable. No use putting me on fmhy anymore. Once I recover, I may reach out again, but if not, you may assume, that I completely retired off of cracking after this incident. Assuming that I may not hear of you again, farewell

**Comment by KraysThePoet** [comment]
Note, that buzzheavier may just unlock files if norwegian police allows them, but yeah above message is just in case they dont
