### ISSUE TITLE
Terranion, a starred terraria wiki, is outdated.

### ISSUE THREAD

**Issue by MegusHooIT** [fmhy/edit#2573]
### Type

Bad sites

### Add additional context

Under the terraria tools section in Gaming Tools, Terranion is a starred site and is described as the terraria wiki. However, as of the latest version of terraria released almost 2 years ago now, it is still outdated. The information provided, while concise, is also not very fully fleshed out compared to the official terraria wiki at https://terraria.wiki.gg which i believe is more maintained, up to date and contains much more useful information instead.

**Comment by nbats** [comment]
thanks for the heads up, I'll get this one starred in its place
