### ISSUE TITLE
Add a Christmas theme to the site on the 25th of December

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2580]
### Type

Site suggestion

### Add additional context

Hello. Last time you couldn't add a Halloween theme because it was simply too late. But, what about this time? Will you add a Christmas theme to the site on the 25th of December? If you do decide to add a theme, thanks.

**Comment by nbats** [comment]
I passed it along to discord, but I cant make any promises any artists will want to go to the effort. Everything we do is community made so if anyone wants to try to take it on and has the know-how they're more than welcome to.
