### ISSUE TITLE
a new invite.

### ISSUE THREAD

**Issue by ieci** [fmhy/edit#2593]
### Type

Site suggestion

### Add additional context

Hi, hope all is well! I'm reaching out regarding an invitation to the FMHY Discord. Thank you.

**Comment by ieci** [comment]
Per the bulletin, "Send a Issue or Pull Request or to our GitHub". Hopefully I'm doing this right!

**Comment by InternetNinjo** [comment]
the invitation to the discord is directly on the wiki itself and this repo itself

on repo it's at the bottom with discord logo
https://github.com/fmhy#-follow
on wiki there's a discord button, 

i don't think you need to create an issue regarding

**Comment by nbats** [comment]
The server is currently semi-private, check here each friday for a new invite

https://rentry.co/fmhy-invite
