### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2594]
### Type

Other

### Add additional context

The discord invite link's not available. So, why are you showing me the apparent invite link while creating an issue?

![2024-11-08 18_38_00-New Issue · fmhy_edit - Brave](https://github.com/user-attachments/assets/5d6ac943-d7f6-4d13-b5e7-2a9b6605d5bc)
![2024-11-08 18_38_28-Discord - Brave](https://github.com/user-attachments/assets/c3d21b5f-ee9c-452a-9cc9-d359251824d0)

Not to mention that the Rentry is also filled with errors.

![384374408-81dad56b-cc83-4bf3-8be3-661062e0ec00](https://github.com/user-attachments/assets/4e1ed0bb-4811-457d-8718-b35584734ea4)

**Comment by VaiCaDep0893** [comment]
The sever has gone semi-private, so expect the admins to remember to create a new invite

**Comment by InternetNinjo** [comment]
@VaiCaDep0893 invite link will be available every friday on the rentry

**Comment by VaiCaDep0893** [comment]
> @VaiCaDep0893 invite link will be available every friday on the rentry

No?
![ảnh](https://github.com/user-attachments/assets/26abae61-0102-450d-aac6-136337cd7b0e)

**Comment by InternetNinjo** [comment]
> > @VaiCaDep0893 invite link will be available every friday on the rentry
> 
> No? And today's friday. That's why I said expect the admins to remember ![ảnh](https://private-user-images.githubusercontent.com/88310371/384394805-26abae61-0102-450d-aac6-136337cd7b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzQ4NDAsIm5iZiI6MTczMTA3NDU0MCwicGF0aCI6Ii84ODMxMDM3MS8zODQzOTQ4MDUtMjZhYmFlNjEtMDEwMi00NTBkLWFhYzYtMTM2MzM3Y2Q3YjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE0MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMWU5ODA3ZjFkNjRjY2RlMGJjNDRkOTE4MTRkYWY3OGExMzRlYTVhOTA1NzVjNjFjYjgxOWNmZTNjNGJkMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CspLZF8e6KbBEhS6-hLa92vPczBBd-iFj42puCmNqZc)

right i forgot

**Comment by VedSonawale** [comment]
Did you guys fixed it? It is still showing invite closed.

**Comment by nbats** [comment]
yeah sorry I over-slept but they're open now

**Comment by kvhjdffv** [comment]
@nbats You closed the issue without even addressing my two suggestions. Could you please, do that?

**Comment by nbats** [comment]
sorry both should be fixed now
