### ISSUE TITLE
Issues with the Rentry

### ISSUE THREAD

**Issue by kvhjdffv** [fmhy/edit#2599]
### Type

Grammar / Markdown

### Add additional context

![2024-11-09 18_02_04-Current Status_ Closed - Brave](https://github.com/user-attachments/assets/d9c6fb44-7d3f-43e5-b276-ddae85886bbd)

**Comment by nbats** [comment]
It leads to our github, where people can make pull requests

**Comment by kvhjdffv** [comment]
@nbats 
First of all, just make it redirect to https://github.com/fmhy/edit/pulls then.

Scond of all, you still haven't addressed the grammatical error.

**Comment by nbats** [comment]
Alright sorry both should be fixed now
