### ISSUE TITLE
Add Tutorial on how to Crack Games

### ISSUE THREAD

**Issue by KraysThePoet** [fmhy/edit#2612]
### Type

Wiki section suggestion

### Add additional context

More specifically, my own tutorials. Nothing big though, only how to use goldberg/SteamAutoCracker/CreamInstaller and where to get goldberg specifically. My original server/Website, where the videos were supposed to be at is now shutting down, and it'd be nice, if those tutorials wouldn't have to be lost in time. Also, I wasnt sure where to put this under, so let me know if "Wiki Section Suggestion" is wrong. By the way, I redid the 2nd tutorial to make sure everything fits and there is no confusion
If you already wanna look at the Tutorials, here they are:
Games with no DRM (How to use Goldberg Emulator basically): https://streamable.com/e7ueex
Games that use the SteamDRM (SAC and CreamInstaller): https://streamtape.com/v/VoOjlQWZ97TKLw4/How_to_use_SAC_%2B_CreamInstaller.mp4

**Comment by nbats** [comment]
thanks for sharing, I'll see if I can find a spot for them
