### ISSUE TITLE
Move the site hunting guide to the FMHY Website

### ISSUE THREAD

**Issue by Alonso287** [fmhy/edit#2652]
### Type

Wiki section suggestion

### Add additional context

I'd suggest moving the [Site Hunting guide](https://reddit.com/r/FREEMEDIAHECKYEAH/w/find-new-sites) from the subreddit to the website, just as we did with the Search post, which is now more accessible via the website, and adding it to the Ecosystem menu.

**Comment by nbats** [comment]
Sounds good I'll get it added
