### ISSUE TITLE
<title> Suggest sites 

### ISSUE THREAD

**Issue by HHO08** [fmhy/edit#2666]
### Type

Site suggestion

### Add additional context

1. Hello FHMY, I want you to add some sites I like your wiki very much and I suggest you add sites to download PPSSPP mods Such as DBZTTTMODS or PPSSPPKing 
2. If it is also possible to add Google CSE to search for mods for games and applications, you can try it yourself: 
https://cse.google.com/cse?cx=a528152a37f34418e#gsc.tab=0

**Comment by nbats** [comment]
thanks for sharing we'll check them out when we can
