### ISSUE TITLE
PrivaZer

### ISSUE THREAD

**Issue by s7xxrs** [fmhy/edit#2667]
### Type

Site suggestion

### Add additional context

https://privazer.com/en/ is an alternative to CCleaner which has been around for many years and is highly recommended by Reddit users.

Personally I used to use BleachBit but PrivaZer is faster and better as BleachBit practically only removes what the [Microsoft PC Manager](https://www.microsoft.com/store/productId/9PM860492SZD?ocid=pdpshare) tool would remove.

It is better, the only disadvantages are:
- NOT open source
- It is freemium not free (the options of the **PRO** version are really irrelevant)
  + **CRACKSurl**

I think it should be starred together with BleachBit as it is practically better.

I hope you can review it and consider it, have a good one :D

**Comment by nbats** [comment]
thanks for sharing we'll check it out when we can
