### ISSUE TITLE
Multi server

### ISSUE THREAD

**Issue by 0x265** [fmhy/edit#2668]
### Type

Site suggestion

### Add additional context

Stumbled upon this site [https://seriestechmovies.icu/](url) its pretty solid

**Comment by InternetNinjo** [comment]
> [https://seriestechmovies.icu/](url) its pretty solid

Note: danish site

**Comment by RaySist1** [comment]
Hi, I was informed that a link to "Series.tech Movies" has been shared here. I am the owner of the site.

For your information, both "Danske film/Danish Movies" and "Premium" use a custom server/player. Our API is also open source. That being said, I’m not sure FMHY has a significant Danish audience. Nonetheless, you’re more than welcome to add the site.

- RaySist

**Comment by InternetNinjo** [comment]
> Hi, I was informed that a link to "Series.tech Movies" has been shared here. I am the owner of the site.
> 
> For your information, both "Danske film/Danish Movies" and "Premium" use a custom server/player. Our API is also open source. That being said, I’m not sure FMHY has a significant Danish audience. Nonetheless, you’re more than welcome to add the site.
> 
>     * RaySist

btw try clicking, it goes to github issue url

**Comment by RaySist1** [comment]
When clicking on what exactly?

on this `* RaySist`

**Comment by InternetNinjo** [comment]
> ### Type
> 
> Site suggestion
> ### Add additional context
> 
> Stumbled upon this site [https://seriestechmovies.icu/](url) its pretty solid

in this lol

**Comment by InternetNinjo** [comment]
> I disabled right-click simply because I find the default context menu visually unappealing and out of place with the design of my site. It disrupts the clean and cohesive experience I want users to have. This is more of a stylistic choice than anything else. I want the site to look and feel polished without interruptions from the default browser interface.
> 
> Even though my API is open source, I chose to disable developer tools because I want to avoid unnecessary distractions for users. The focus should remain on the content, not on exploring how it’s built.

the reasons you're saying are simply just for regular users and not for the testers or devs, because we do the testing to see if it's worth it to add the site in wiki or not.

these practices will just make the site look like closed source.

**Comment by InternetNinjo** [comment]
> I disabled right-click simply because I find the default context menu visually unappealing and out of place with the design of my site. It disrupts the clean and cohesive experience I want users to have. This is more of a stylistic choice than anything else. I want the site to look and feel polished without interruptions from the default browser interface.
> 
> Even though my API is open source, I chose to disable developer tools because I want to avoid unnecessary distractions for users. The focus should remain on the content, not on exploring how it’s built.

@nbats i think this is enough reason to not keep this site on wiki

**Comment by nbats** [comment]
lets at least try it out, we don't have a lot of options for Danish sites so if it works well it may be worth adding
