### ISSUE TITLE
Remove G-MEH Premium Bypass

### ISSUE THREAD

**Issue by LolHarambe33** [fmhy/edit#2674]
### Type

Bad sites

### Add additional context

The [premium bypass](https://gmehpremium.pages.dev/) for [G-MEH](https://g-meh.com/) in the Audio Plugins section of Music / Podcasts / Radio is no longer working, all download links lead to a message that just states "To keep yourself safe, visit g-meh.com for downloads."

**Comment by nbats** [comment]
I'll get it removed in the next update, thanks for letting us know
