### ISSUE TITLE
Adding more Arabic sites 

### ISSUE THREAD

**Issue by HHO08** [fmhy/edit#2678]
### Type

Site suggestion

### Add additional context

Hi FMHY, I really like your wiki, but I noticed a lack of Arabic pages.

Sorry for the inconvenience, can you add more Arabic sites?

Like:  
https://www.downloadcomputergames.net/
for downloading computer games 
 

and this is just an example 

as well as sites for watching movies and series, you can find some of them on Quora or Reddit

https://www.quora.com/What-sites-are-the-best-to-watch-English-movie-in-arabic-subtitles

**Comment by InternetNinjo** [comment]
> ### Type
> 
> Site suggestion
> ### Add additional context
> 
> Hi FMHY, I really like your wiki, but I noticed a lack of Arabic pages.
> 
> Sorry for the inconvenience, can you add more Arabic sites?
> 
> Like: https://www.downloadcomputergames.net/ for downloading computer games
> 
> and this is just an example
> 
> as well as sites for watching movies and series, you can find some of them on Quora or Reddit
> 
> https://www.quora.com/What-sites-are-the-best-to-watch-English-movie-in-arabic-subtitles

I have thorughly checked the "downloadcomputergames" site and it has a lot of red flags, please remove that link

we'll test others in the mean time

**Comment by HHO08** [comment]
I'm sorry, man
