### ISSUE TITLE
Add website: https://blockblastcheat.com/

### ISSUE THREAD

**Issue by chanmankong** [fmhy/edit#2684]
### Type

Site suggestion

### Add additional context

This website provides a tool that can calculate the best moves in Block Blast game to help users get high scores

**Comment by InternetNinjo** [comment]
Cheat Software or Application that gives unfair advantage is not allowed here sorry @chanmankong

**Comment by WNnitro** [comment]
@InternetNinjo im pretty sure that only applies to multiplayer games

**Comment by nbats** [comment]
true but this is still too niche to add
