### ISSUE TITLE
[New Tool Submissions]

### ISSUE THREAD

**Issue by grillgamesh** [fmhy/edit#2687]
### Type

Site suggestion

### Add additional context

I have two tools hosted here; 
https://github.com/grillgamesh/CENGAGE_RIPPER (this one is semi-working, and needs work done; but I can't do any more work as I lack the knowledge; Pull requests are welcome, and I'll even transfer the repo if someone more skilled wishes to take over.)

https://github.com/grillgamesh/NHentai-Favorites-Archiver (works perfectly; just needs some patience)

Instructions for use of both tools are on the repo. Let me know if these are valid submissions!

**Comment by nbats** [comment]
thanks for sharing, I'll add both to our list to keep an eye on
