### ISSUE TITLE
Ellipsus

### ISSUE THREAD

**Issue by FilzaMechery** [fmhy/edit#2710]
### Type

Site suggestion

### Add additional context

# Ellipsus
https://ellipsus.com/ is a great tool for writers and editors.
It has great support for collaboration and is also very nice to use.
 
![Screenshot 2024-12-07 171328](https://github.com/user-attachments/assets/f6a5c7c0-777b-40fd-b211-8370ed90bd47)
They have a discord-https://discord.com/invite/5brTBGZQfS
-Thank you guys!

**Comment by nbats** [comment]
ty we'll check it out soon

**Comment by FilzaMechery** [comment]
Thank you for fmhy! And accepting my suggestion!
