### ISSUE TITLE
İnat TV link is nuked. new one:

### ISSUE THREAD

**Issue by gototheskinny** [fmhy/edit#2731]
### Type

Site suggestion

### Add additional context

old one: İnat TV : https://inattv146.link
[inattv184.link](https://inattv184.link/) 
inattv184.link

**Comment by nbats** [comment]
ty we'll check it out

**Comment by gototheskinny** [comment]
> ty we'll check it out

Hey everyone, I realize I was wrong to report the link here, but I wanted to share my thoughts. This site is problematic because the links change constantly, but it's an excellent resource for Turkish content. Unfortunately, Warner Bros.' local DMCA representatives (formerly Blutv) are really aggressive and hostile with DMCA claims.

This app serves as a sort of safe haven. Please keep it in the FMHY repo, but don't include the link—it's pointless since it’s always getting blocked in Turkey. Instead, you can find the latest link on the İnat TV Twitter account, which they update regularly. Please consider adding this app back to the Turkish section.

Tw account:
[https://twitter.com/inattvapk](https://twitter.com/inattvapk)
