### ISSUE TITLE
Suggest on submitting new Text-to-3D from Microsoft Research

### ISSUE THREAD

**Issue by Matthew-Eucaristo** [fmhy/edit#2738]
### Type

Site suggestion

### Add additional context

I think this is cool to start 3D Generation section in Artificial Intelligence Wiki.
Site: https://trellis3d.github.io/
Github: https://github.com/Microsoft/TRELLIS

Thanks <3

**Comment by nbats** [comment]
ty for sharing, we'll take a look soon

**Comment by Matthew-Eucaristo** [comment]
Thanks
