### ISSUE TITLE
HaxMac is not trusted

### ISSUE THREAD

**Issue by gradygambrell** [fmhy/edit#2752]
### Type

Bad sites

### Add additional context

The website haxmac.cc cannot be trusted because of malware hidden via "fake download" button. Please remove it completely. This cannot be fixed/removed with an adblocker (i.e. AdGuard, UBO etc.)

Source: 
https://www.virustotal.com/gui/url/a30762607dda104aabc267404911efa18a17ca0e40a0ec42bbc5e711cb65c0cf
https://moonlock.com/pirate-sites-cleanmymac-photoshop
https://tria.ge/241224-vfhh3asngm/behavioral1
https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fhaxmac.cc%2F

![browserling-screenshot](https://github.com/user-attachments/assets/36f53198-308b-4781-86b0-d80d00931ff3)

**Comment by nbats** [comment]
I'm on the site right now with ubo and theres no fake button, make sure your ubo filters are updated 

![image](https://github.com/user-attachments/assets/705234e1-0154-4a34-b8c7-957d3c4d10b6)
