### ISSUE TITLE
Pulse

### ISSUE THREAD

**Issue by FilzaMechery** [fmhy/edit#2758]
### Type

Site suggestion

### Add additional context

[pulse](https://2016.makemepulse.com/) is a site that would fall under the miscellaneous category.
It is very fun and enjoyable.
![Screenshot 2024-12-26 174240](https://github.com/user-attachments/assets/436fb2ae-1473-4068-a36a-a647e42b0aa3)
Side note- The music heals my soul and might be the best thing ive heard

**Comment by nbats** [comment]
thank you we'll check it out soon
