### ISSUE TITLE
Restore Linux Difficulty Chart

### ISSUE THREAD

**Issue by SplendidPiePizza** [fmhy/edit#2769]
### Type

Site suggestion

### Add additional context

Before there is Linux Difficulty Chart and it is gone without reason. What happened?
![linuxdifficultychart](https://github.com/user-attachments/assets/ebb4644a-1f66-4d72-95a3-e87c9a62f33b)

**Comment by nbats** [comment]
It isn't maintained and people felt there are better sites for recommendations like this
